sudo: required
services:
  - docker
before_install:
  - docker pull alpine:3.6

script:
  - docker build -t $DOCKER_USERNAME/ss-test -f alpine/Dockerfile .

after_success:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PWD
  - docker push $DOCKER_USERNAME/ss-test