sudo: required
services:
  - docker
before_install:
  - docker pull alpine:3.8
  - echo $DOCKER_PWD | docker login -u $DOCKER_USERNAME --password-stdin
  - chmod +x build.sh

script:
  - ./build.sh

notifications:
  email: false