sudo: required
services:
  - docker
before_install:
  - docker pull alpine:3.6

script:
  - docker build -t $DOCKER_USERNAME/ss-test -f alpine/Dockerfile .

after_success:
  - echo $DOCKER_PWD | docker login -u $DOCKER_USERNAME --password-stdin
  - docker push $DOCKER_USERNAME/ss-test