sudo: required
services:
  - docker
before_install:
  - docker pull alpine:3.6
  - echo $DOCKER_PWD | docker login -u $DOCKER_USERNAME --password-stdin


script:
  - docker build -t $DOCKER_USERNAME/ss-libev -f ss-libev/Dockerfile .

after_success:
  - docker push $DOCKER_USERNAME/ss-libev